
* Nome do Software (ou Biblioteca):
- TRATAMENTO ESTATÍSTICO DE DADOS GEOQUÍMICOS.

* Resumo e/ou informação extra: 
Em experimentos realizados no laboratório de geoquímica, observa-se que algumas amostras apresentam um valor discrepante com relação as demais.
Por exemplo as percentagens das frações de NSO saturados e aromáticos.
No laboratório tem-se n pesquisadores que utilizam a amostra X, por exemplo, para calcular suas percentagens de saturados, aromáticos e NSO. Sabe-se que cada pesquisador pode encontrar valores diferentes destas percentagens para essa mesma amostra. Tais valores normalmente variam pouco de experimento para experimento, mas há casos em que a percentagem varia consideravelmente. As porcentagens calculadas pelo pesquisador Y apresentam um valor bastante diferente das percentagens de SAT e ARO com relação ao que os outros pesquisadores encontraram. Acredita-se, portanto, que tais valores sejam outliers. A partir desta suspeita é preciso então comprová-la, o que normalmente é feito através dos testes: Teste do escore z modificado, Teste de Grubbs, Teste de Dixon, Teste de Cochran e Teste de Doerffel.
A modelagem foi criada com a intenção de propor um tratamento estatístico de dados geoquímicos a partir da regressão linear, testes de hipótese e identificação de valores anômalos (outliers).
Um exemplo de caso de uso padrão envolve a escolha de um método estatístico para tratar os dados geoquímicos.
1. Selecionar o tratamento estatístico.
2. Fornecer dados geoquímicos.
3. Aplicar o tratamento.
4. Analisar resultados.

* Versão: 
- 1.0.

* Data:
- 2013/2 - segundo semestre.
  
* Autor de Contato:
- André Duarte Bueno <andreduartebueno@gmail.com>

* Lista dos Autores:
- Márcio Luís Carvalho Araújo
- Tamires dos Santos Soares
- Thiago Rocha Gomes
- André Duarte Bueno <andreduartebueno@gmail.com>

* Áreas de pesquisa vinculadas: 
- Geoquímica
- Estatística Aplicada
- Modelagem Matemática Computacional

* Vinculo com: 
- Trabalho da disciplina de programação prática.

* Paradigmas: 
- POO - Programação Orientada a Objeto (códigos em C++)

* Tipo de Interface: 
- Terminal e gráfica (gnuplot).

* Plataformas Suportadas: 
- Windows e GNU/Linux e Mac OS X (não testada).

* Linguagens Utilizadas: 
- C++ 11.

* Bibliotecas Utilizadas (dependências):
- CGnuplot - https://github.com/ldsc/CGnuplot

* Softwares utilizados (dependências)
- gnuplot http://www.gnuplot.info/

* Tipo de Licença:
- GPL
- Entre em contato com o Prof. André Duarte Bueno
  andreduartebueno@gmail.com
  para que o mesmo gere um novo projeto no github do ldsc para você (e sua equipe) possam trabalhar na nova versão.
- Se este projeto tem como número de versão 1.0 a nova versão deverá ser 2.0.
- Os nomes dos autores originais deve ser preservada na nova versão, ou seja, adicione a informação do número da versão, os nomes dos membros da nova equipe, mas jamais apague os nomes dos autores originais (isto seria plágio).
  
* Links:

